### ISSUE TITLE
DE Australia - pop up /disclaimer

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#10]
text to be sent by DEA team

**Comment by rowanwins** [comment]
I'm currently using

---------------------------------
As a condition of using this website, users should understand and must accept that the information and data provided on the DE Africa Map:
- is entirely dependent on the accuracy of the information and data which has been provided by the third data custodians
- is not necessarily complete
- sometimes is general in nature
- should not be relied on in place of independent research and professional advice.

Geoscience Australia and Data61 do no warrant, and are not liable for the accuracy of the information and data on the DE Africa Map.

The information displayed on the DE Africa Map is for general informational purposes only, and is not intended to provide any commercial, financial or legal advice. Any information in connection with the DE Africa may not be appropriate to your individual needs. You must exercise your own independent, skill, care and judgement with respect to how you use the information displayed on the DE Africa Map. As a condition of using the DE Africa Map, you must comply with all applicable laws, regulations and third party rights (including, without limitation, laws regarding the import or export of data or software, privacy and local laws).

---------------------------------

**Comment by rowanwins** [comment]
> I do not want people to have to accept a disclaimer to use the site.  This disclaimer text is fine and appropriate to be buried behind a disclaimer hyperlink should people feel the desire to go and read it.  This will not be a popup.

Not in popup form, will put in the about pages somewhere
