### ISSUE TITLE
DE Australia - Update Tool tips wording

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#100]
Update tool tips wording with the new edits available [HERE](https://teams.microsoft.com/l/file/A89D9F81-02E0-4968-9749-4490C07A1F78?tenantId=0fe05593-19ac-4f98-adbf-0375fce7f160&fileType=docx&objectUrl=https%3A%2F%2Fcsiroau.sharepoint.com%2Fsites%2FWebDataPlatformsgroup%2FShared%20Documents%2FGeneral%2FTerria%2FDigital%20Earth%20Australia%20_%20Africa%2FDigital%20Earth%20Australia%20Map%2F2021-05-17_DE%20Australia%20-%20Tool%20Tips%20wording.docx&baseUrl=https%3A%2F%2Fcsiroau.sharepoint.com%2Fsites%2FWebDataPlatformsgroup&serviceName=teams&threadId=19:bb5b1646ad984aed9d16a0d10dd36ef3@thread.skype&groupId=624ec5d0-4407-4c62-ab3a-74808556dacd)

**Comment by wibily** [comment]
https://github.com/TerriaJS/terriajs/pull/5559
https://github.com/TerriaJS/terrace/pull/170
