### ISSUE TITLE
Investigation: differences between charts behaviour for DEA data services

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#106]
For DEA Waterbodies, the user can click on multiple waterbodies and then click "Expand" on the Feature Info popup to get a unique chart for each (e.g orange and blue in the left image). However, doing the same thing for DEA Coastlines only ever adds a single orange chart which replaces the previous chart (e.g. orange in the right image).
I am almost certain that this used to work on version 7 of Terria, but I can't work out why it still works for DEA Waterbodies but not Coastlines. I've created a minimal example below: the two charts are set up slightly differently due to different input data formats, but both add a unique ID and title to the chart (a UUID for Waterbodies, a coordinate string for Coastlines):

Waterbodies: 
<chart id='{{uid}}' title='Waterbody {{uid}}' preview-x-label='Date' sources='{{#terria.urlEncode}}{{timeseries}}{{/terria.urlEncode}}'  column-names='Time,Percentage of total surface area (not volume) observed as wet,Wet Pixel Count' column-units='Date of satellite observation,%,#'></chart>

Coastlines:
<chart id='{{terria.coords.latitude}}, {{terria.coords.longitude}}' title='DEA Coastlines ({{#terria.formatNumber}}{maximumFractionDigits:4}{{terria.coords.latitude}}{{/terria.formatNumber}}, {{#terria.formatNumber}}{maximumFractionDigits:4}{{terria.coords.longitude}}{{/terria.formatNumber}})' y-column='Distance (metres) relative to 2019 coastline' x-column='Year' column-units='{{terria.timeSeries.units}}' preview-x-label='Year'>Year,Distance (metres) relative to 2019 coastline\n1988,{{dist_1988}}\n1989,{{dist_1989}}\n1990,{{dist_1990}}\n1991,{{dist_1991}}\n1992,{{dist_1992}}\n1993,{{dist_1993}}\n1994,{{dist_1994}}\n1995,{{dist_1995}}\n1996,{{dist_1996}}\n1997,{{dist_1997}}\n1998,{{dist_1998}}\n1999,{{dist_1999}}\n2000,{{dist_2000}}\n2001,{{dist_2001}}\n2002,{{dist_2002}}\n2003,{{dist_2003}}\n2004,{{dist_2004}}\n2005,{{dist_2005}}\n2006,{{dist_2006}}\n2007,{{dist_2007}}\n2008,{{dist_2008}}\n2009,{{dist_2009}}\n2010,{{dist_2010}}\n2011,{{dist_2011}}\n2012,{{dist_2012}}\n2013,{{dist_2013}}\n2014,{{dist_2014}}\n2015,{{dist_2015}}\n2016,{{dist_2016}}\n2017,{{dist_2017}}\n2018,{{dist_2018}}\n2019,{{dist_2019}}</chart>

Share link: https://terria-cube.terria.io/#share=s-qIAG425mArkFPtL1KP9Mxhw4vrW
Minimal config: https://gist.github.com/robbibt/bbe67f4b0d5c4a9ca4dc9a91071bca15 

![image](https://user-images.githubusercontent.com/18452161/132148721-52bb0626-7829-4726-9774-a0c6c0494eda.png)
![image](https://user-images.githubusercontent.com/18452161/132148755-cdbdaef1-d22c-447a-a564-0f55247d105d.png)

**Comment by robbibt** [comment]
Looks like this will be solved by: https://github.com/TerriaJS/terriajs/pull/5795
