### ISSUE TITLE
DE Australia - Mar 22 Release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#111]
- [x] https://github.com/terriajs/terriajs/issues/5427
- [x] https://github.com/terriajs/terriajs/issues/4692
- [x] https://github.com/TerriaJS/terriajs/issues/5646 
- [x] https://github.com/terriajs/terriajs/issues/4620 https://github.com/TerriaJS/terriajs/pull/6234
- [x] https://github.com/terriajs/terriajs/issues/3827

**Comment by nf-s** [comment]
Story test link https://de-australia.dev.saas.terria.io/story/DEACoastlines

**Comment by nf-s** [comment]
Dev and test have been deployed

**Comment by AnaBelgun** [comment]
tested and looks ok.
