### ISSUE TITLE
Vanity URL for Land cover story

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#113]
DEA maps would like to share a Land cover story more widely using a vanity url similar to Coastlines story. 
This URL: https://maps.dea.ga.gov.au/#share=s-kDaIywrPsYaY657bNyHhoNE4PVv
to become
this URL: https://maps.dea.ga.gov.au/#share=s-DEALandCover

**Comment by tephenavies** [comment]
Completed
