### ISSUE TITLE
DE Aus - update DEA Land Cover story url

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#115]
to update the DEA Land Cover story url https://maps.dea.ga.gov.au/story/DEALandCover with a new share link https://maps.dea.ga.gov.au/#share=s-pHV7HTGpfoyyXGpIEhIAiMxk9YL

**Comment by nf-s** [comment]
Done https://maps.dea.ga.gov.au/#share=s-DEALandCover
