### ISSUE TITLE
Allow setting a custom request limit for different servers

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#12]
- Due to issues with services performance due to a cap on requests (max 3) 
- Done for DE Africa: https://github.com/TerriaJS/de-africa-map/pull/19 
- needs done for all maps where DE Satellite Imagery is included

**Comment by AnaBelgun** [comment]
this will be part of release if decided at meeting on 17 Sep 19 with DEA

**Comment by AnaBelgun** [comment]
@steve9164 to implement a change to 12-24 tile requests limit TBC

**Comment by steve9164** [comment]
I've talked with @kring and done some testing and I don't think there is a significant difference in performance between limiting to 6 or 12 concurrent requests, as there is when using Chrome limited to 3 or a different browser which is limited to 6. We should work towards including the Cesium bug fix in all apps and not use custom request limits for DEA services.
