### ISSUE TITLE
Add Help in the top right menu 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#14]
Based on discussions recorded here: https://docs.google.com/document/d/1Y7Z1EwwkzuBrOgrqowxauJ0-p4v70oVGyoDztOSwoUY/edit

- [x] add help button in the top right hand side menu similar to https://soe.terria.io/

- [x] fix the issue with users not being able to return to previous step (in case they are at step 2)

Add the following options/guides:

- [ ] Explore map data

- [ ] Interact with the data. To include instructions on general interaction with datasets and more specifically for satellite imagery

- [x] Zoom in to show satellite, flag to user he needs to wait to load to get imagery

- [x] Calendar - time

- [x] Zoom to location and filter by location

- [ ] Splitter

other?

- [ ] Add your own data

- [ ] Change map settings

- [ ] Share/Export/Print

**Comment by AnaBelgun** [comment]
temporarily (for GEO Week) point the help button to the About - Help pages http://de-australia.terria.io/help/help.html

**Comment by rowanwins** [comment]
Done
