### ISSUE TITLE
DE Australia - link to social media channels from UI

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#19]
@philipgrimmett what would be the best option to link to social media channels from the UI: 
Twitter - https://twitter.com/GeoscienceAus
Facebook - https://www.facebook.com/GeoscienceAustralia
Youtube - https://www.youtube.com/user/GeoscienceAustralia
LinkedIn - https://au.linkedin.com/company/geoscience-australia

**Comment by rowanwins** [comment]
On the about pages this is easy - not so easy in the TerriaMap interface esp before GeoWeek

**Comment by philipgrimmett** [comment]
**Invision comp**
https://invis.io/MWULVQ1XH4P#/391034809_about-001

Given limited real estate on the map, I'd suggest we display social media icon button in an 'about' modal that launches when users click on the 'about' map button. This modal provides a brief description of the project goals and links to more information, social channels etc. The benefit of this would be users can source key information about each map without being sent away from the map itself. The risk is that less users click through to the full about, help, privacy docs.

**Comment by AnaBelgun** [comment]
will reissue this when redesign
