### ISSUE TITLE
DEA - July 2019 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#2]
- [x] update to latest terriajs

- [x] update to latest terria server 3.0.1 which fixes bug with shortening url when sharing TerriaJS/terriajs#3510 - to be double checked by @steve9164 

- [x] logos/styling - https://github.com/TerriaJS/dea-map/issues/1

**Comment by soyarsauce** [comment]
@AnaBelgun updated terriajs & server @ http://de-australia.terria.io/
