### ISSUE TITLE
Remove satellite imagery from terria-cube config

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/de-australia-map#26]
Get rid of this category
https://github.com/TerriaJS/de-australia-map/blob/master/wwwroot/init/terria-cube.json#L9402

**Comment by GypsyBojangles** [comment]
Would you also be able to remove:

**Comment by GypsyBojangles** [comment]
"Leo has also suggested removing the monthly and annual options on the hydro layers for the DE-Australia map"
