### ISSUE TITLE
Add Disclaimer pop up

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#34]
Here’s our disclaimer text for the DEA Maps popup window.

The information displayed on the DEA Maps (the “Service”) is for general informational purposes only, and is not intended to provide any commercial, financial, or legal advice.

The Service provides access to a range of data sets and tools, some of which are in development (beta). All data and tools are provided on an “as is” and “with all faults” basis without any warranty whatsoever. Geoscience Australia and Data61 do not warrant that these data sets and tools shall meet any requirements or expectations, or that the will be fit for any intended purposes. 

Geoscience Australia and Data61 assumes no responsibility for errors or omissions in the contents of the Service and reserves the right to make additions, deletions, or modification to the contents on the Service at any time without prior notice.

Geoscience Australia and Data61 does not guarantee the accuracy, relevance, timeliness, or completeness of any information or data available through the Service or on linked external websites.

See full terms and conditions [here].

A couple of other bits and pieces:

-	the link in the final sentence of the disclaimer should take users to our existing T&Cs
-	the button to close the modal and progress to the maps portal should say “Acknowledge”
-	the other option should be “Cancel” button with the behaviour being to close the window/tab, i.e. the whole maps window not just the modal, if that option is selected.

**Comment by soyarsauce** [comment]
All updated, with the exception of the last point:

> the link in the final sentence of the disclaimer should take users to our existing T&Cs
Linked with page anchor specifically to the T&Cs

>the button to close the modal and progress to the maps portal should say “Acknowledge”
Done

>the other option should be “Cancel” button with the behaviour being to close the window/tab, i.e. the whole maps window not just the modal, if that option is selected.
This isn't possible in web browsers - I've simply made it redirect to https://www.ga.gov.au/dea if a user clicks cancel.
