### ISSUE TITLE
DE Australia - Nov 2019 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#35]
- [x] add disclaimer: https://github.com/TerriaJS/de-australia-map/issues/34

- [x] update Blended service: https://github.com/TerriaJS/de-australia-map/issues/30

- [ ] add social media links: https://github.com/TerriaJS/de-australia-map/issues/19

**Comment by soyarsauce** [comment]
Disclaimer is released now: https://de-australia.terria.io/

**Comment by soyarsauce** [comment]
@rowanwins 
Recent blended service PR:
https://github.com/TerriaJS/NationalMap-Catalog/pull/154/files#diff-4b6b4e30495ad03e4242392d21a847ebR230
