### ISSUE TITLE
Waterbodies data - disclaimer + sharing issue - development

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/de-australia-map#38]
https://github.com/TerriaJS/de-australia-map/issues/37

**Comment by soyarsauce** [comment]
Not yet decided on whether we are implementing in master or mobx
Implementing in mobx will mean making terria-cube ready for mobx

**Comment by AnaBelgun** [comment]
Follow up from Vic and Rowan discussion: 
- Can you left align the text with the “Charts” title underneath it
- Once the above is done, reduce the top and bottom padding to match the left hand side padding
- Give the text link an underline
- Full stop at end of sentence
- Background colour to be #9A4B4B

**Comment by rowanwins** [comment]
Underway in #3930

**Comment by rowanwins** [comment]
Done
