### ISSUE TITLE
Onboarding designs - testing 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#40]

**Comment by soyarsauce** [comment]
"What's new" is being considered as part of this testing. Semi-related: https://github.com/TerriaJS/terriajs/issues/3806

**Comment by alyce** [comment]
So current scope for this testing is:
- Onboarding
- Delta
- What's New
- Waterbodies update

**Comment by AnaBelgun** [comment]
Based on discussion held on 6 March, UX team recommends doing testing on live prototypes for both Onboarding and Delta. 

Timeline has changed accordingly and design testing for Onboarding was cancelled.
