### ISSUE TITLE
Delta v2 - designs 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#45]
Following agreement with DEA and UI developers, Delta v2 designs to be finalised by 20 March if possible.

**Comment by vicborgy** [comment]
Here are the final Delta designs ready for development & testing:
https://invis.io/SYWP0UQWK8V

**Comment by vicborgy** [comment]
Here is the Sketch file: https://drive.google.com/open?id=1-2z2QV3XNHbDGN99u4xM1vf69yjIU21h&authuser=design@victorborg.com.au&usp=drive_fs

**Comment by AnaBelgun** [comment]
Designs for v2 are done. 

@vicborgy @soyarsauce 
Should the v2 designs are changed either during development or after testing, 
we should submit new tickets with the respective version (v2.1 etc) and what changed (more like a doc version control) and then link to the epic. In this way we know where we are with the designs and dev iterations. 
Unless you know of a different /better method.

**Comment by soyarsauce** [comment]
Yeah @AnaBelgun I think we just go with new ticket with version number in title and link to epic, some system is better than nothing
