### ISSUE TITLE
MobX DEA - show imagery as dots instead of lines on charts 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#48]
To replicate the behaviour of showing dates as dots on water discharge charts, we need to replace the lines currently available on MobX for charts

**Comment by na9da** [comment]
This feature already exists in `mobx`. Last week, I created a PR with some bug fixes for it - https://github.com/TerriaJS/terriajs/pull/4383

To enable the service for individual satellite imagery datasets we need to configure them with:
`"chartType": "momentPoints"`, just like in master.

**Comment by AnaBelgun** [comment]
awesome work @na9da

**Comment by AnaBelgun** [comment]
@steve9164 Rowan has implemented the dots for DE Au in master in case you need more info

**Comment by AnaBelgun** [comment]
Yes, the imagery is shown as dots on current DE Australia MobX implementation: 
 - http://de-australia.saas.terria.io/
- http://de-australia.saas.terria.io/#share=s-bAd0CCuTjXvCu4QyfBAckvUApmy
