### ISSUE TITLE
DE Australia - July 2020 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#52]
- [x] geojson catalog items converted to mobx-catalogs

- [x] Specific to DEA: Waterbodies charts display the same behaviour and warning message: http://de-australia.terria.io/#share=s-q2fCou4W0OVpWyZXUBkzqvFvnJz; - [ ] Copy implementation of warning message when opening waterbodies and click on expand chart - https://github.com/TerriaJS/de-australia-map/issues/49; needs this: https://github.com/TerriaJS/terriajs/pull/4479/ 

- [x] Delta v3 implementation - post user testing undertaken 19-21/05/2020 - https://github.com/TerriaJS/terriajs/issues/4390; PR https://github.com/TerriaJS/terriajs/pull/4515 

- [x] Delta v3 - has to work with ODC DEA OWS set up as well as with NCI GSKY service

**Comment by soyarsauce** [comment]
Released on http://de-australia.saas.terria.io/ now.

Includes
- geojson support & catalog items: http://de-australia.saas.terria.io/#share=s-eUajtxsK3bpNFRgfmoHa5pj7vly
- (chart sharing is broken)
  - 1. click share link
  - 2. click a waterbody
  - 3. expand chart
  - 4. see disclaimer
  - waterbodies chart display & disclaimer: http://de-australia.saas.terria.io/#share=s-hBfNhIPkB5I3ydWiL0eiaiRKqzr

<img width="1778" alt="image" src="https://user-images.githubusercontent.com/9134432/87393843-20b96580-c5f2-11ea-9ba4-d6fe9d6f1fef.png">

- delta v3 implementation included
- delta v3 support for both ODC DEA OWS & GSKY OWS: 
http://de-australia.saas.terria.io/#share=s-A8e1d51prLPd4ETmPuisQIAywhY

**Comment by AnaBelgun** [comment]
done
