### ISSUE TITLE
Coastlines legend shown 3 times in the workbench 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#54]
When new Coastlines WMS https://geoserver.dea.ga.gov.au/geoserver/wms is tested on a non-mobx maps such as https://terria-cube.terria.io/ https://terria-cube.terria.io/#share=s-jDQF9nKRUykVhlMxnReWasLN14F, the legend appears 3 times in the workbench. 

The legend has been uploaded here: https://data.dea.ga.gov.au/projects/coastlines/coastlines_legend.png

![image](https://user-images.githubusercontent.com/18452161/87266944-ba591800-c509-11ea-9706-0b6f1875d64f.png)

**Comment by robbibt** [comment]
Hi @AnaBelgun, it seems like this issue is coming directly from the GeoServer WMS instead of Terria; we've been able to work around this issue by supplying a custom legend URL in the Terria config. I'd be happy for you to close this unless you have another reason to keep it open.

**Comment by AnaBelgun** [comment]
great thank you @robbibt for letting us know
