### ISSUE TITLE
DE Australia - Catalogue maintenance on DEAu on mobx

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#56]
The DEA team would like to continue to maintain the catalogue on the http://de-australia.saas.terria.io/. 
Is that a good candidate for Catalogue Editor? Is there a different way for them to retain that capability?

**Comment by soyarsauce** [comment]
See https://github.com/TerriaJS/de-africa-map/issues/49#issuecomment-663315957

**Comment by AnaBelgun** [comment]
clarified with DEA
