### ISSUE TITLE
DE Australia - Coastlines - shorter url for demo and broadcasting by DEA team

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#62]
DEA team would like to start using vanity url shortner for broadcasting work on some specific datasets.
The first example will be the use of the short url for the Coastlines data, to be published and disseminated to Government and other users on 17th of Sep. 

There are 2 stages: 
1) 15 Sep 2020 - enable the http://maps.dea.ga.gov.au/**#share=s-DEACoastlines** when DEA team advises the data publication and its url 
2) 28 Sep 2020 - work and release a more elegant shortening of urls which will transform the above url closer to http://maps.dea.ga.gov.au/**DEACoastlines** (https://github.com/TerriaJS/terriajs/issues/4692)

**Comment by AnaBelgun** [comment]
@steve9164 is it possible on the 15th of Sep once we receive the advice from DEA team, to enable this url for the coastlines data: http://maps.dea.ga.gov.au/#share=s-DEACoastlines?

**Comment by soyarsauce** [comment]
We've already successfully tested the concept with the beta link

**Comment by AnaBelgun** [comment]
Done by @steve9164 on Fri 17 Sep
