### ISSUE TITLE
DE Australia - revise logos and styling

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#7]
Landing page:
- [x] delete Prototype from logos section

- [x] add GA logo https://drive.google.com/drive/u/0/folders/1BpfjZvjI2QPk5254n6RUQgbdG7l_Jc7w

- [x] replace Data61 logo with the recent one (CSIRO Data61) https://drive.google.com/drive/u/0/folders/19XZfBUS4xPdCMeDObPaa5Vn2aSnWOifi

**Comment by rowanwins** [comment]
Here's the new brandbar - do we want to send it to DEA for approval @AnaBelgun ? 
![Brandbar](https://user-images.githubusercontent.com/6735870/67449600-6bf7a680-f666-11e9-99d6-db0e33840606.png)
