### ISSUE TITLE
DE Australia - Waterbodies - dots on chart line 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#72]
Ability to put dots on the line chart to show where the valid observations are. 

This is a symbology change, so quite different to the Water discharge level example. 

Instead of a line chart the irrigators would like a line with markers chart. Here is a very basic example using excel. Data is on the left. 

Please note that there are fewer points in the DEA waterbodies time series than there are in the imagery stack (surface area isn't calculated for cloud affected / partial coverage of waterbody), so the plot symbology needs to be drawn from the data in the CSV's not from the imagery service stack at that location. 

![image](https://user-images.githubusercontent.com/18452161/102945830-04134900-4513-11eb-9019-de5010e64ee3.png)

**Comment by AnaBelgun** [comment]
Context: 
Q: 
Vanessa, just to clarify a bit your second point.
Do you mean to have the same functionality like we currently have for Water discharge levels (BoM) and Satellite Imagery (i.e. show me the imagery for this location/water sensor point on the graph)?
Below the BoM water + satellite (with dots on the chart showing where the imagery is).
![image](https://user-images.githubusercontent.com/18452161/102946014-8bf95300-4513-11eb-8f4e-8553aaa13aa1.png)
![image](https://user-images.githubusercontent.com/18452161/102946026-9287ca80-4513-11eb-9cef-c4cc79f587bf.png)

A: 
Hi Ana, yes to your second point, having that styling applied to DEA Waterbodies is what we're after aesthetically.

Please note that there are fewer points in the DEA waterbodies time series than there are in the imagery stack (surface area isn't calculated for cloud affected / partial coverage of waterbody), so the plot symbology needs to be drawn from the data in the CSV's not from the imagery service stack at that location.

Kind regards, Leo.

**Comment by KeyboardSounds** [comment]
Done, just needs to be deployed.

**Comment by AnaBelgun** [comment]
Update 11 Aug 2021: 
it appears that the dots on the charts for waterbodies have disappeared since last update of the catalogue (last week)

![image](https://user-images.githubusercontent.com/18452161/129116220-ce3a251a-dfb9-486a-8218-6c97a71fbdbf.png)

**Comment by wibily** [comment]
Ana: quite important as users are using this

**Comment by na9da** [comment]
That's easy to do with a catalog config change
![image](https://user-images.githubusercontent.com/1430/130534012-c726343d-4271-440b-832e-5367e4d2f626.png)

However we need a small change to Terria so that the satellite imagery dots will line up correctly along with the waterbodies dots.
![image](https://user-images.githubusercontent.com/1430/130535942-3bc270dd-e4c3-4949-9541-e2b28b93cc6a.png)

I'll create a PR for that. 

Also, ideally we need to assign different glyphs for the satellite & waterbody dots so that users can tell them apart properly. I'll check if we can add support to do that.

**Comment by na9da** [comment]
Sub tickets:
- [x] https://github.com/TerriaJS/terriajs/issues/5758
- [x] https://github.com/TerriaJS/terriajs/issues/5759
- [x] Deployed saas with latest terriajs (v8.1.x)
- [ ] Updated config

**Comment by na9da** [comment]
The config change for this is adding `chart-type='lineAndPoint'` to the `<chart>` component in the feature info template of "DEA Waterbodies" as seen in this [catalog definition](https://gist.github.com/na9da/657916be03e1541629f2018501e80a4d#file-waterbodies-json-L10).
