### ISSUE TITLE
DE Australia - Waterbodies - include metadata in chart download

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/de-australia-map#75]
As a user,
When I download a CSV of a chart of Waterbodies data, I want the metadata from the dataset to be included
So that when browsing those files on my computer later, I know which dataset is which and I don't lose the associated metadata.

---

Follows on from https://github.com/TerriaJS/de-australia-map/issues/71

Metadata in a CSV won't currently be included when the data is downloaded from the Chart panel, and GA requests that it should be. Because a chart CSV download could include multiple datasets, the metadata from each dataset should be included along with information on which column (original dataset) it's associated with.

**Comment by KeyboardSounds** [comment]
Metadata lives in comments. eg the first line of
```
# this is metadata
this, is, the, actual, csv
```
Rather than trying to get our current CSV parsing code to output comments as well as CSV data, I suggest we write our own "CSV comment parser" to extract them, and only run it when a chart is downloaded.

**Comment by AnaBelgun** [comment]
this is not confirmed as a requirement after dots on chart work was completed. 
Will close for now, but can re-open if re-confirmed.
