### ISSUE TITLE
Help pop up - bottom right corner - doesn't show

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#87]
Steps to reproduce (to double check); it just might be the case the user clicked on "don't show me this again" on landing page welcome modal and also clicked on "ok, got it" when the Help button showed in the right bottom corner
- Go to http://beta.de-australia.terria.io/
- Help (bottom corner) doesn't seem to show

**Comment by AnaBelgun** [comment]
Ana to check in a different browser and respon dto client

**Comment by steve9164** [comment]
Open site in Private Window (FF) or Incognito window (Chrome) to test experience for first time users

**Comment by AnaBelgun** [comment]
it does for new users who haven't clicked "dismiss'
