### ISSUE TITLE
DE Australia - Catalogue org update

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#93]
- [ ] DEA data catalogue needs updating: names, org etc

DEA team comments: 
DEA Maps could be re-structured (essentially closely following the structure and names used in CMI). 
Baseline satellite data (* Probably remove "baseline" to be more user friendly) 
    |---> DEA Surface Reflectance
          |---> ... (* Finding a nice way to organise all of our satellite layers will be the trickiest thing)
    |---> DEA Surface Reflectance Geomedian (* In CMI this is located in "Land and vegetation", but it could make more sense here?)

Inland waterbodies
    |---> DEA Water Observations (WOfS)
          |---> ...
    |---> DEA Waterbodies

Land and vegetation
    |---> DEA Fractional Cover
          |---> ...
    |---> DEA Mangroves
    |---> Barest Earth

Sea, ocean and coastline
    |---> DEA Coastlines
    |---> DEA Intertidal (NIDEM, ITEM)
          |---> DEA Intertidal Elevation
          |---> DEA Intertidal Extents
    |---> DEA High Low Tide Image (HTLC)
          |---> DEA Low Tide Image
          |---> DEA High Tide Image

Hazards
    |---> DEA Hotpots

Other (*not a CMI category, but would be useful for reducing clutter)
    |---> Camden Environmental Monitoring Project 
    |---> InSARWater Regulations Data (BoM)

**Comment by nf-s** [comment]
Done - now handled by them https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/terria/dea.json
