### ISSUE TITLE
NEII (Water + Satellite) feature - observation dates shown by default 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#94]
Comments from DEA team: Observation dates to be shown by default 

Deliverable – Show observation dates on chart for Waterbodies data 
Workflow 
•	Go to Digital Earth Australia waterbodies - http://de-australia.terria.io/#share=s-5HHstdpaaLVlEc3x0YX0Kby1FEi
•	Click on a waterbody and expand the chart
 
![image](https://user-images.githubusercontent.com/18452161/119453493-d4df5d00-bd7a-11eb-861b-e496c4141f01.png)

•	Once chart is expanded, show the dates when observations were recorded, similar to how observation dates (of satellite imagery) are shown on the Water gauges charts
![image](https://user-images.githubusercontent.com/18452161/119453591-ef193b00-bd7a-11eb-9b46-4a568b11b2a9.png)
•	The dates’ dots are recorded in a CSV – the basis of the data layer; the dots would indicate the dates when water was observed; they are ‘cleaned’ up of cloud/obstructions 
![image](https://user-images.githubusercontent.com/18452161/119453672-035d3800-bd7b-11eb-81d3-a89ec4f5109b.png)

**Comment by na9da** [comment]
Fixes:
- [x] Config change to make dots appear on chart
       Test link: https://de-australia.terria.io/#share=s-44EZIKLkA8wv3Rw9GvXZQpeQagJ
- [ ] Code change to fix styling & click behavior when hovering the points - https://github.com/TerriaJS/terriajs/pull/5553

**Comment by na9da** [comment]
PR with styling changes merged to `next` branch.
