### ISSUE TITLE
DE Australia - Split related bug 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#96]
Splitter-related bug here. To reproduce:
Open link: http://beta.de-australia.terria.io/#share=s-1nZ6rsHBaiXp3FrwTdV5obCav5f
Press "Compare" up the top right
Turn off the main "Digital Earth Australia Coastlines" layer
Turn on "Rates of change statistics" layer and set to "Right"
Turn on "Annual coastlines" layer and set to "Left"
Both layers now display only on "Both", not "Left" or "Right". I'm not sure what is happening here... it seems like the second and third layers are adopting the default that is set to the top layer.

Can't seem to reproduce this when loading three satellite layers: http://beta.de-australia.terria.io/#share=s-9kVghkxv56hI498NbFFOfGbsZXx

It seems like when the "split screen mode" dialogue appears, this bug doesn't. However I'm not sure why it appears for other satellite imagery layers but not the DEA Coastlines layers.

**Comment by nf-s** [comment]
I'm pretty sure I fixed this, need to confirm though

**Comment by nf-s** [comment]
This is fixed
