### ISSUE TITLE
Story v2.0 - Charts handling - Story loses feature info chart 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#97]
The only discrepancy in the story https://maps.dea.ga.gov.au/#share=s-DEACoastlines&playStory=1 is the 10th "Time series charts of coastal change" story panel, which seems to have lost its pop-up chart (current on the left, desired on the right). The weird thing is that this used to appear on V7 but it seems to have gone from there too. It would have been nice to include but it's not a critical issue as the text includes a call to action ("For more detailed information about any of these types of coastal change, click on any labelled point."). 

![image](https://user-images.githubusercontent.com/18452161/114633502-f3762100-9d03-11eb-8dc0-1d3104cec1db.png)

![image](https://user-images.githubusercontent.com/18452161/114633526-fe30b600-9d03-11eb-8baa-67d3307ae5c3.png)

**Comment by na9da** [comment]
Upon inspection, this doesn't look like a bug. I think the story scene didn't capture the feature info panel for some reason. I have recaptured the scene with an open feature info panel (of my choice) in this share link - https://maps.dea.ga.gov.au/#share=s-GSWdkUDFKQZSSN38Ll2c4qHvQ3

If that looks ok I'll update the share link to point to this new story I captured.

**Comment by na9da** [comment]
This should be fixed now, opening https://maps.dea.ga.gov.au/#share=s-DEACoastlines&playStory=1  will show a feature info popup with chart for the 10th scene.
