### ISSUE TITLE
DE Australia - option for DEA team to update catalogue & test data services

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#98]
DEA Team: 
-  we do need somewhere to test our web services and catalog
-  now with the v8 release we don't really have a convenient/persistent spot
- until earlier this week, we updated the terria cube catalog with the services/features we want to test to share with stakeholders

Some options: 
1) update terriacube to v8 and keep that as DEA testing site (public)
2) give access to dev/test DE AU to DEA team (not public)

**Comment by nf-s** [comment]
Related to https://github.com/TerriaJS/saas/issues/132

**Comment by nf-s** [comment]
**Nick to expand on the following**

- Currently we are storing SaaS catalogs and map-configs in a public GitHub repo https://github.com/TerriaJS/saas-catalogs-public
- Probably not ready to link to catalog JSON files in other repos
- Probably will keep repo public and let customers make PRs to update catalogs in https://github.com/TerriaJS/saas-catalogs-public

**Comment by AnaBelgun** [comment]
hi @steve9164 @nf-s we might need to elevate this to high priority end of next week because of changes to DE Au and DE Af catalogues

**Comment by AnaBelgun** [comment]
sent instructions by email on 29 June 2021
